### ISSUE TITLE
spark_client_kernel provisioning error

### ISSUE THREAD

**Issue by arbackus** [BigDataRepublic/bdr-infra-stack#20]
`TASK [spark_client_kernel : set_fact] ******************************************
fatal: [bdr-data-science-box]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0\n\nThe error appears to have been in '/vagrant/common/components/spark_client_kernel/tasks/main.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}`

**Comment by stefanvanwouw** [comment]
Cannot reproduce
