### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by ghost** [BigDataRepublic/bdr-infra-stack#5]
The box starts up in the 'data-science-box' dir, while this dir will be overwritten (deleting anything in it) in case of terminate and rerun of the box. Need to add a convenient dir structure on top (2 steps) of the 'data-science-box' dir, like data, notbeooks, etc.

**Comment by stefanvanwouw** [comment]
@arbackus @gerbenoostra You have linked/proposed to a data science dir layout before. Could you please post a suggestion?

We could wire the mounted dir to ../../ for example, meaning it would mount My Documents if you downloaded the bdr-infra-stack to that location. Then there is the additional option of ensuring certain directories exist in the mounted dir ( like the ones @coenseinen suggested).

**Comment by gerbenoostra** [comment]
I just forked the data science layout of cookie cutter in our repo, which
shows the preferred directory layout.

**Comment by stefanvanwouw** [comment]
I'll pick this up later.
